# Hardened Preview Worker Kubernetes Manifests
# ServiceAccount, Security Context, Resource Limits, Health Probes, RBAC

apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-worker
  namespace: preview-worker
  labels:
    app: preview-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-worker
  namespace: preview-worker
  labels:
    app: preview-worker
    version: v1.0.0
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: preview-worker
  template:
    metadata:
      labels:
        app: preview-worker
        version: v1.0.0
    spec:
      serviceAccountName: preview-worker
      imagePullSecrets:
        - name: regcred  # Replace with your registry secret name if using private registry
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: preview-worker
          image: ghcr.io/mobius-org/mobius-preview-worker:1.0.0  # CRITICAL: Replace with actual registry/image:tag
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PREVIEW_QUEUE_NAME
              value: "preview-jobs"
            - name: PREVIEW_WORKER_CONCURRENCY
              value: "2"
            - name: HEALTH_PORT
              value: "3000"
            - name: LOG_LEVEL
              value: "info"
            # Example of reading from secrets (uncomment and adjust as needed)
            # - name: REDIS_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: preview-worker-secrets
            #       key: REDIS_URL
            # - name: API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: preview-worker-secrets
            #       key: API_KEY
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/preview/worker/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
            timeoutSeconds: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/preview/worker/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
            successThreshold: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
            - name: cache
              mountPath: /app/cache
              readOnly: false
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: preview-worker
  namespace: preview-worker
  labels:
    app: preview-worker
spec:
  type: ClusterIP
  selector:
    app: preview-worker
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP