apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: preview-worker
  namespace: preview-worker
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: preview-worker
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    relabelings: []