version: '3.8'

services:
  mobius-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:staging
    container_name: mobius-ci-staging
    environment:
      - NODE_ENV=staging
    volumes:
      # Mount verification reports directory
      - ./verification-reports:/app/verification-reports
      # Mount logs directory
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "echo", "OK"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: "no"
    networks:
      - mobius-network

networks:
  mobius-network:
    driver: bridge
