version: '3.8'

services:
  mobius-api:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:staging
    container_name: mobius-api-staging
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=staging
      - PORT=5001
    volumes:
      # Mount uploads directory for persistent storage
      - ./uploads:/app/uploads
      # Mount logs directory
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mobius-network

networks:
  mobius-network:
    driver: bridge
