version: '3.8'

services:
  mobius-api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:latest
    container_name: mobius-api-ci
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:5001/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - ci-network
    restart: unless-stopped

networks:
  ci-network:
    driver: bridge
