services:
  api:
    build:
      context: ./src/api-ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=container
      - USE_MOCKS=true
      - PORT=5001
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 5s
      timeout: 3s
      retries: 6
    restart: "no"