version: '3.8'

services:
  api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:5001/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    container_name: mobius-api-ci
    networks:
      - mobius-ci

networks:
  mobius-ci:
    driver: bridge