services:
  api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - mobius-ci

networks:
  mobius-ci:
    driver: bridge