version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:local
    container_name: mobius-api
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IMAGE_EXTRACTOR_API_KEY=${IMAGE_EXTRACTOR_API_KEY}
      - OUTPUT_DIR=/app/src/api/uploads/MobiusGames
    volumes:
      - uploads:/app/src/api/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mobius-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: mobius-client:local
    container_name: mobius-client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mobius-network

volumes:
  uploads:
    driver: local

networks:
  mobius-network:
    driver: bridge
