version: '3.8'
services:
  api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5001/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
