services:
  mobius-api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: mobius-api-ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=staging
      - PORT=5001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      # Optional: mount logs directory if needed
      - ./logs:/app/logs:rw
    networks:
      - mobius-ci

networks:
  mobius-ci:
    driver: bridge