version: "3.8"

services:
  api-ci:
    build:
      context: ./src/api-ci
      dockerfile: Dockerfile.ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=container
      - USE_MOCKS=true
      - PORT=5001
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5001/health"]
      interval: 5s
      timeout: 3s
      retries: 6
    restart: "no"