services:
  mobius-api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:local
    container_name: mobius-api-ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=ci
      - MOCK_MODE=true
      - PORT=5001
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5001/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - mobius-network

networks:
  mobius-network:
    driver: bridge
