services:
  api-ci:
    build:
      context: ./src/api-ci
      dockerfile: Dockerfile.ci
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=container
      - USE_MOCKS=true
      - PORT=5001
    restart: "no"