version: '3.8'

services:
  mobius-api:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: mobius-api-staging
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=staging
      - PORT=5001
    volumes:
      # Mount uploads directory for file operations
      - ./uploads:/app/uploads
      - ./verification-reports:/app/verification-reports
      - ./ci-run-logs:/app/ci-run-logs
    networks:
      - mobius-staging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mobius-staging:
    driver: bridge

volumes:
  # Persistent volumes for development data
  mobius-uploads:
  mobius-reports: