version: '3.8'

services:
  mobius-api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:local
    container_name: mobius-api-staging
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=staging
      - PORT=5001
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); });"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - mobius-network

networks:
  mobius-network:
    driver: bridge
