services:
  mobius-api-ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    image: mobius-api-ci:staging
    container_name: mobius-api-staging
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - mobius-ci
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mobius-ci:
    driver: bridge
    name: mobius-ci-network