version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=staging
      - PORT=5001
      - ALLOWED_TOKEN=${ALLOWED_TOKEN}
    volumes:
      - ./src:/app/src
    command: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 5