services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=container
      - PORT=5001
      - USE_MOCKS=true
      # Optional environment variables - uncomment and set as needed
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - IMAGE_EXTRACTOR_API_KEY=${IMAGE_EXTRACTOR_API_KEY}
      # - API_KEY=${API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mobius-network

networks:
  mobius-network:
    driver: bridge