groups:
- name: mobius.rules
  rules:
  - alert: HighErrorRate
    expr: sum by (route) (rate(http_request_duration_seconds_count{status=~"5.."}[5m]))
          / sum by (route) (rate(http_request_duration_seconds_count[5m])) > 0.02
    for: 5m
    labels: { severity: page }
    annotations:
      summary: "High 5xx error rate on {{ $labels.route }}"
      description: "5xx > 2% over 5m. Investigate recent deploys or upstreams."

  - alert: LatencyP95TooHigh
    expr: histogram_quantile(0.95, sum by (le, route) (rate(http_request_duration_seconds_bucket[5m]))) > 1
    for: 10m
    labels: { severity: ticket }
    annotations:
      summary: "P95 latency > 1s for {{ $labels.route }}"
      description: "Consistently elevated latency may indicate saturation or regressions."

  - alert: TTSCachingDropped
    expr: rate(tts_cache_hits_total[10m]) / rate(tts_requests_total[10m]) < 0.2
    for: 15m
    labels: { severity: ticket }
    annotations:
      summary: "TTS cache hit ratio low"
      description: "Cache hit ratio < 20%. Check cache key/versioning and storage health."