#!/bin/bash
# Lifecycle Management Export Script
# Exports deployment lifecycle data and metrics

set -euo pipefail

EXPORT_DIR="${EXPORT_DIR:-exports}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
EXPORT_NAME="lcm_export_${TIMESTAMP}"

log() {
  echo "[LCM-EXPORT] $(date '+%Y-%m-%d %H:%M:%S') - $*"
}

export_deployment_metadata() {
  local export_path="$1"
  
  log "Exporting deployment metadata"
  
  cat > "$export_path/deployment_metadata.json" << EOF
{
  "export_timestamp": "$TIMESTAMP",
  "git_commit": "$(git rev-parse HEAD 2>/dev/null || echo 'unknown')",
  "git_branch": "$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')",
  "git_tag": "$(git describe --tags --exact-match 2>/dev/null || echo 'none')",
  "environment": "${DEPLOY_ENV:-unknown}",
  "node_version": "$(node --version 2>/dev/null || echo 'unknown')",
  "npm_version": "$(npm --version 2>/dev/null || echo 'unknown')",
  "system_info": {
    "hostname": "$(hostname 2>/dev/null || echo 'unknown')",
    "os": "$(uname -s 2>/dev/null || echo 'unknown')",
    "arch": "$(uname -m 2>/dev/null || echo 'unknown')"
  }
}
EOF
  
  log "✓ Deployment metadata exported"
}

export_backup_history() {
  local export_path="$1"
  
  log "Exporting backup history"
  
  if [ -d "backups" ]; then
    echo "[" > "$export_path/backup_history.json"
    local first=true
    
    find backups -name "manifest.json" | sort | while read -r manifest; do
      if [ "$first" = true ]; then
        first=false
      else
        echo ","
      fi
      cat "$manifest"
    done >> "$export_path/backup_history.json"
    
    echo "]" >> "$export_path/backup_history.json"
    log "✓ Backup history exported"
  else
    echo "[]" > "$export_path/backup_history.json"
    log "No backup history found"
  fi
}

export_deployment_logs() {
  local export_path="$1"
  
  log "Exporting deployment logs"
  
  # Export GitHub Actions logs if available
  if [ -n "${GITHUB_RUN_ID:-}" ]; then
    echo "GitHub Actions Run ID: $GITHUB_RUN_ID" > "$export_path/deployment_context.txt"
    echo "GitHub Repository: ${GITHUB_REPOSITORY:-unknown}" >> "$export_path/deployment_context.txt"
    echo "GitHub Workflow: ${GITHUB_WORKFLOW:-unknown}" >> "$export_path/deployment_context.txt"
    echo "GitHub Actor: ${GITHUB_ACTOR:-unknown}" >> "$export_path/deployment_context.txt"
  fi
  
  # Export system logs (last 100 lines)
  if command -v journalctl >/dev/null 2>&1; then
    journalctl --lines=100 --no-pager > "$export_path/system_logs.txt" 2>/dev/null || true
  fi
  
  log "✓ Deployment logs exported"
}

export_health_metrics() {
  local export_path="$1"
  
  log "Exporting health metrics"
  
  # Export current system metrics
  cat > "$export_path/health_metrics.json" << EOF
{
  "timestamp": "$TIMESTAMP",
  "disk_usage": "$(df . | tail -1 | awk '{print $5}' | sed 's/%//')",
  "memory_usage": "$(free | grep Mem | awk '{printf "%.1f", $3/$2 * 100.0}' 2>/dev/null || echo 'unknown')",
  "load_average": "$(uptime | awk -F'load average:' '{print $2}' | xargs 2>/dev/null || echo 'unknown')",
  "process_count": "$(ps aux | wc -l)"
}
EOF
  
  # Test health endpoint if possible
  if [ -n "${BASE_URL:-}" ]; then
    local health_response
    if health_response=$(curl -s --max-time 5 "$BASE_URL/health" 2>/dev/null); then
      echo "$health_response" > "$export_path/health_endpoint_response.json"
      log "✓ Health endpoint response captured"
    fi
  fi
  
  log "✓ Health metrics exported"
}

create_export_summary() {
  local export_path="$1"
  
  log "Creating export summary"
  
  local file_count=$(find "$export_path" -type f | wc -l)
  local total_size=$(du -sh "$export_path" | cut -f1)
  
  cat > "$export_path/README.md" << EOF
# MOBIUS Deployment Lifecycle Export

**Export Date:** $(date)
**Export ID:** $EXPORT_NAME
**Files Count:** $file_count
**Total Size:** $total_size

## Contents

- `deployment_metadata.json` - Git and system information
- `backup_history.json` - Historical backup manifest data
- `deployment_context.txt` - CI/CD context information
- `health_metrics.json` - System and application health metrics
- `system_logs.txt` - Recent system logs (if available)
- `health_endpoint_response.json` - Health endpoint response (if available)

## Usage

This export contains lifecycle data for deployment troubleshooting and audit purposes.
All sensitive information has been excluded.

Generated by MOBIUS Deployment Framework
EOF
  
  log "✓ Export summary created"
}

main() {
  local export_path="$EXPORT_DIR/$EXPORT_NAME"
  
  log "Starting lifecycle management export"
  log "Export path: $export_path"
  
  mkdir -p "$export_path"
  
  export_deployment_metadata "$export_path"
  export_backup_history "$export_path"
  export_deployment_logs "$export_path"
  export_health_metrics "$export_path"
  create_export_summary "$export_path"
  
  # Create compressed archive
  tar -czf "$export_path.tar.gz" -C "$EXPORT_DIR" "$EXPORT_NAME"
  rm -rf "$export_path"
  
  log "✓ LCM export completed: $export_path.tar.gz"
  echo "LCM_EXPORT_PATH=$export_path.tar.gz" >> $GITHUB_OUTPUT 2>/dev/null || true
}

main "$@"
