name: Deploy Preview Worker
description: Deploys the preview worker to Kubernetes with configurable options
inputs:
  namespace:
    description: Kubernetes namespace to deploy to
    required: false
    default: preview-worker
  manifests-path:
    description: Path to Kubernetes manifests
    required: false
    default: k8s/preview-worker
  image-tag:
    description: Docker image tag to use
    required: true
  kubeconfig:
    description: Base64 encoded kubeconfig
    required: true

runs:
  using: composite
  steps:
    - name: Setup kubeconfig
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kubeconfig }}" | base64 --decode > ~/.kube/config

    - name: Update manifests with image tag
      shell: bash
      run: |
        echo "Updating manifests with image tag: ${{ inputs.image-tag }}"
        
        # Update manifests
        find ${{ inputs.manifests-path }} -type f \( -name "*.yaml" -o -name "*.yml" \) -exec sed -i.bak \
          -e "s|YOUR_REGISTRY/mobius-preview-worker:ci|${{ inputs.image-tag }}|g" \
          -e "s|ghcr.io/mobius-org/mobius-preview-worker:1.0.0|${{ inputs.image-tag }}|g" {} \;
        
        # Remove backup files
        find ${{ inputs.manifests-path }} -type f -name "*.bak" -delete

    - name: Deploy to Kubernetes
      shell: bash
      run: |
        kubectl apply -f ${{ inputs.manifests-path }} -n ${{ inputs.namespace }}
        kubectl rollout status deployment/preview-worker -n ${{ inputs.namespace }} --timeout=300s

    - name: Run smoke tests
      shell: bash
      run: |
        kubectl run --rm -i --restart=Never smoke-test --image=curlimages/curl --command -- sh -c \
          "curl -fsS http://preview-worker.${{ inputs.namespace }}.svc.cluster.local/healthz || exit 1"