name: API Smoke Tests (CI)

on:
  push:
    branches:
      - main
      - 'ci/**'
  pull_request:
    branches:
      - main

jobs:
  api-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Node (for verification script)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install verification dependencies
        run: npm ci --omit=dev

      - name: Run repo verification
        run: node scripts/verify-clean-genesis.js

      - name: Build CI image
        run: docker build -f Dockerfile.ci -t mobius-api-ci:ci .

      - name: Start staging compose
        run: docker compose -f docker-compose.staging.yml up -d --build

      - name: Wait for health (small delay)
        run: |
          timeout 30 bash -c 'until curl -sSf http://localhost:5001/health >/dev/null; do sleep 1; done'

      - name: Run smoke tests
        run: ./scripts/ci/smoke-tests.sh http://localhost:5001 15 2
        continue-on-error: false

      - name: Collect compose logs
        if: failure()
        run: docker compose -f docker-compose.staging.yml logs --timestamps > compose-logs.log || true

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-smoke-test-artifacts
          path: |
            smoke-tests.log
            compose-logs.log
            verification-reports/

      - name: Teardown compose (always)
        if: always()
        run: docker compose -f docker-compose.staging.yml down --volumes --remove-orphans
