name: Frontend CI Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'client/src/**'
      - 'client/package.json'
      - 'client/.eslintrc.json'
  push:
    branches: [ main ]
    paths:
      - 'client/src/**'
      - 'client/package.json'
      - 'client/.eslintrc.json'

jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: |
          npm run lint
          
      - name: Run unit tests
        run: |
          npm test -- --runInBand --detectOpenHandles --verbose

      - name: Run WebSocketGuard specific tests
        run: |
          npx jest src/utils/__tests__/WebSocketGuard.test.js --runInBand --detectOpenHandles --verbose