name: Golden Approve

on:
  workflow_dispatch:
    inputs:
      games:
        description: "Comma-separated list of games (e.g. hanamikoji,sushi-go,love-letter)"
        required: true
        default: "hanamikoji"
      perOs:
        description: "Use per-OS baselines"
        type: boolean
        default: true

permissions:
  contents: read

concurrency:
  group: golden-approve-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  approve:
    name: Approve baselines (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install FFmpeg (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install FFmpeg (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ffmpeg

      - name: Install FFmpeg (Windows)
        if: runner.os == 'Windows'
        run: choco install ffmpeg -y --no-progress

      - name: Install dependencies
        run: npm ci

      - name: Render previews (replace with your real commands)
        run: |
          npm run render:proxy || true

      - name: Verify preview exists
        run: |
          if [ ! -f "out/preview.mp4" ]; then
            echo "Error: Preview file not found at out/preview.mp4"
            echo "Please ensure the render step completed successfully"
            exit 1
          fi
        shell: bash

      # ... rest of the file remains unchanged ...