name: Tutorial Visibility CI

on:
  push:
    branches:
      - feat/tutorial-visibility
  pull_request:
    branches:
      - main
      - feat/tutorial-visibility

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Run linter
        run: |
          cd client
          npm run lint -- --max-warnings=0

      - name: Run tests
        run: |
          cd client
          npm test

      - name: Build production
        run: |
          cd client
          npm run build